#!/bin/bash
# Web - Brave Web Browser
xdg-mime default brave-browser.desktop x-scheme-handler/http
xdg-mime default brave-browser.desktop x-scheme-handler/https

# Music - Celluloid
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/3gpp
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/3gpp2
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/aac
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/ac3
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/amr
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/amr-wb
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/basic
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/dv
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/eac3
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/flac
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/m4a
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/midi
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/mp1
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/mp2
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/mp3
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/mp4
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/mpeg
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/mpegurl
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/mpg
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/ogg
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/opus
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/scpls
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/vnd.dolby.heaac.1
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/vnd.dolby.heaac.2
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/vnd.dolby.mlp
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/vnd.dts
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/vnd.dts.hd
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/vnd.rn-realaudio
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/wav
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/webm
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-aac
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-aiff
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-ape
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-flac
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-gsm
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-it
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-m4a
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-matroska
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-mod
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-mp1
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-mp2
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-mp3
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-mpeg
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-mpegurl
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-mpg
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-ms-asf
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-ms-wma
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-musepack
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-pn-aiff
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-pn-au
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-pn-realaudio
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-pn-wav
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-real-audio
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-realaudio
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-s3m
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-scpls
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-shorten
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-speex
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-tta
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-vorbis
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-vorbis+ogg
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-wav
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-wavpack
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-xm
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/mp4a-latm
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/mpeg3
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/vorbis
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/wave
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-mpeg-3
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-ogg
xdg-mime default io.github.celluloid_player.Celluloid.desktop audio/x-oggflac

# Video - Celluloid
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/3gp
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/3gpp
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/3gpp2
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/divx
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/dv
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/fli
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/flv
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/mp2t
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/mp4
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/mp4v-es
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/mpeg
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/mpeg-system
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/msvideo
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/ogg
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/quicktime
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/vnd.mpegurl
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/vnd.rn-realvideo
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/webm
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-avi
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-flc
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-fli
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-flv
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-m4v
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-matroska
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-mpeg
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-mpeg-system
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-mpeg2
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-ms-asf
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-ms-wm
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-ms-wmv
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-ms-wmx
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-msvideo
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-nsv
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-ogm+ogg
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-theora
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-theora+ogg
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/vivo
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/vnd.divx
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-anim
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-flic
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-mng
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-ms-afs
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-ms-asx
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-ms-wvx
xdg-mime default io.github.celluloid_player.Celluloid.desktop video/x-ms-wvxvideo

# Photos - Image Viewer (Xviewer)
xdg-mime default xviewer.desktop image/bmp
xdg-mime default xviewer.desktop image/gif
xdg-mime default xviewer.desktop image/jpeg
xdg-mime default xviewer.desktop image/jpg
xdg-mime default xviewer.desktop image/pjpeg
xdg-mime default xviewer.desktop image/png
xdg-mime default xviewer.desktop image/svg+xml
xdg-mime default xviewer.desktop image/svg+xml-compressed
xdg-mime default xviewer.desktop image/tiff
xdg-mime default xviewer.desktop image/vnd.wap.wbmp
xdg-mime default xviewer.desktop image/webp
xdg-mime default xviewer.desktop image/x-bmp
xdg-mime default xviewer.desktop image/x-gray
xdg-mime default xviewer.desktop image/x-icb
xdg-mime default xviewer.desktop image/x-icns
xdg-mime default xviewer.desktop image/x-ico
xdg-mime default xviewer.desktop image/x-pcx
xdg-mime default xviewer.desktop image/x-png
xdg-mime default xviewer.desktop image/x-portable-anymap
xdg-mime default xviewer.desktop image/x-portable-bitmap
xdg-mime default xviewer.desktop image/x-portable-graymap
xdg-mime default xviewer.desktop image/x-portable-pixmap
xdg-mime default xviewer.desktop image/x-xbitmap
xdg-mime default xviewer.desktop image/x-xpixmap

# Word - LibreOffice Writer
xdg-mime default libreoffice-writer.desktop application/msword
xdg-mime default libreoffice-writer.desktop application/rtf
xdg-mime default libreoffice-writer.desktop application/vnd.ms-works
xdg-mime default libreoffice-writer.desktop application/vnd.oasis.opendocument.text
xdg-mime default libreoffice-writer.desktop application/vnd.oasis.opendocument.text-template
xdg-mime default libreoffice-writer.desktop application/vnd.openxmlformats-officedocument.wordprocessingml.document
xdg-mime default libreoffice-writer.desktop application/vnd.stardivision.writer
xdg-mime default libreoffice-writer.desktop application/vnd.wordperfect
xdg-mime default libreoffice-writer.desktop application/x-abiword

# Spreadsheet - LibreOffice Calc
xdg-mime default libreoffice-calc.desktop application/msexcel

# PDF - Document Viewer (Xreader)
xdg-mime default xreader.desktop application/pdf

# Source Code - gedit
xdg-mime default org.gnome.gedit.desktop application/javascript
xdg-mime default org.gnome.gedit.desktop application/x-httpd-php3
xdg-mime default org.gnome.gedit.desktop application/x-httpd-php4
xdg-mime default org.gnome.gedit.desktop application/x-httpd-php5
xdg-mime default org.gnome.gedit.desktop application/x-m4
xdg-mime default org.gnome.gedit.desktop application/x-php
xdg-mime default org.gnome.gedit.desktop application/x-ruby
xdg-mime default org.gnome.gedit.desktop application/x-shellscript
xdg-mime default org.gnome.gedit.desktop application/xml
xdg-mime default org.gnome.gedit.desktop text/css
xdg-mime default org.gnome.gedit.desktop text/turtle
xdg-mime default org.gnome.gedit.desktop text/x-c++hdr
xdg-mime default org.gnome.gedit.desktop text/x-c++src
xdg-mime default org.gnome.gedit.desktop text/x-chdr
xdg-mime default org.gnome.gedit.desktop text/x-csharp
xdg-mime default org.gnome.gedit.desktop text/x-csrc
xdg-mime default org.gnome.gedit.desktop text/x-diff
xdg-mime default org.gnome.gedit.desktop text/x-dsrc
xdg-mime default org.gnome.gedit.desktop text/x-fortran
xdg-mime default org.gnome.gedit.desktop text/x-java
xdg-mime default org.gnome.gedit.desktop text/x-makefile
xdg-mime default org.gnome.gedit.desktop text/x-pascal
xdg-mime default org.gnome.gedit.desktop text/x-perl
xdg-mime default org.gnome.gedit.desktop text/x-python
xdg-mime default org.gnome.gedit.desktop text/x-sql
xdg-mime default org.gnome.gedit.desktop text/x-vb
xdg-mime default org.gnome.gedit.desktop text/yaml

# File Manager - Nemo
xdg-mime default nemo.desktop inode/directory

# Plain Text - gedit
xdg-mime default org.gnome.gedit.desktop text/plain
