autoboot_delay="0"
utouch_load="YES"
kern.vty=vt
kern.geom.label.disk_ident.enable="0"
kern.geom.label.gptid.enable="0"
cryptodev_load="YES"
zfs_load="YES"
virtio_load="YES"
virtio_pci_load="YES"
#virtio_blk_loadvirtio_load="YES"
virtio_pci_load="YES"
virtio_blk_load="YES"
if_vtnet_load="YES"
virtio_balloon_load="YES"
snd_hda_load="YES"
snd_driver_load="YES"
#kldload snd_driver
