# Blacklist file for slpkg.
# Packages listed here will not be upgraded, removed,
# or installed by slpkg.

# WARNING: Ignoring packages during builds, installations,
# or upgrades may cause issues in some cases. Use this feature
# with caution and only when absolutely necessary.

# You can add packages using regular expressions.
# Example to blacklist all Python 2 packages:
# "python2"

# To blacklist a specific package using a regex pattern:
# "^package_name$"

# Example:
# PACKAGES = ["python2", "^python3-build$"]

PACKAGES = ["mint"]
