[Greeter]
theme-name=Gruvbox-Dark-BL
icon-theme-name=gruvbox-dark-icons-gtk
cursor-theme-name=Gruvbox-White
clock-format=%a, %-e %b %-l:%M %p 
background=/usr/share/backgrounds/wallpapersden.com_linux-retro_5120x2880.jpg
draw-user-backgrounds=false
