sendmail_enable="NONE"
hostname="FreeBSD"
ifconfig_vtnet0="DHCP"
sshd_enable="YES"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="NO"
zfs_enable="YES"
dbus_enable="YES"
hald_enable="YES"
lightdm_enable="YES"
linux_enable="NO"
ubuntu_enable="YES"
