[theme_info]
name=Gruvbox-Dark
description=Gruvbox dark theme
version=0.1
author=Enindu Alahapperuma <enindu@gmail.com>
url=https://github.com/enindu/dotfiles

[named_styles]
default=#ebdbb2;#282828;false;false
error=#282828;#fb4934;true

# Editor styles
selection=#ebdbb2;#665c54;false;true
current_line=#ebdbb2;#3c3836;true
brace_good=#ebdbb2;#98971a;true;false
brace_bad=#ebdbb2;#cc241d;true;false
margin_line_number=#a89984;#282828
margin_folding=#a89984;#282828
fold_symbol_highlight=#282828
indent_guide=#a89984
#caret=#ebdbb2;#ebdbb2;true
marker_line=#504945;#fabd2f
marker_search=#504945;#83a598
marker_mark=#504945;#b8bb26
call_tips=#928374;#ebdbb2;false;false
white_space=#928374;#ebdbb2;true;false

# Programming languages
comment=#928374
comment_doc=#928374
comment_line=comment
comment_line_doc=comment_doc
comment_doc_keyword=comment_doc
comment_doc_keyword_error=comment_doc
number=#d3869b
number_1=number
number_2=number_1
type=#fabd2f;;false
class=type
function=#b8bb26
parameter=function
keyword=#fe8019;;false
keyword_1=keyword
keyword_2=#fe8019;;false
keyword_3=keyword_1
keyword_4=keyword_1
identifier=default
identifier_1=identifier
identifier_2=identifier_1
identifier_3=identifier_1
identifier_4=identifier_1
string=#b8bb26
string_1=string
string_2=string_1
string_3=default
string_4=default
string_eol=#504945;#928374
character=string_1
backticks=string_2
here_doc=string_2
label=default,bold
preprocessor=#8ec07c
regex=number_1
operator=#d3869b
decorator=string_1,false
other=#83a598

# Markup languages
tag=#fabd2f
tag_unknown=tag,false
tag_end=tag,false
attribute=#fe8019
attribute_unknown=attribute,false
value=string_1
entity=default

line_added=#98971a
line_removed=#cc241d
line_changed=#d79921
