# Set Compiler Flags for All Languages
COMMON_FLAGS="-march=native -O2 -pipe"

# Set Same Common Flags
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# Set Number of Current Jobs
MAKEOPTS="-j16 -l17"

# Set Global Use Flags
USE="${USE} desktop-portal gnome-keyring gstreamer icu networkmanager pulseaudio \
	-gdm -gnome-shell -nautilus"
#USE="-gdm -gnome-shell -nautilus \
#	alsa desktop-portal gnomekeyring gstreamer icu networkmanager pulseaudio"

# Accept Packages in Testing
#ACCEPT_KEYWORDS="~amd64"

# Accept All Licenses
ACCEPT_LICENSE="*"

# Require signatures
FEATURES="${FEATURES} parallel-fetch parallel-install getbinpkg binpkg-request-signature"

# Set 5 Fastest Gentoo Mirrors
GENTOO_MIRRORS="http://download.nus.edu.sg/mirror/gentoo/ \
    https://download.nus.edu.sg/mirror/gentoo/ \
    http://gentoo.aditsu.net:8000/ \
    http://mirrors.aliyun.com/gentoo/ \
    https://mirrors.aliyun.com/gentoo/"

# Set Language Internationalization
LINGUAS="en"

# Set New Portage Repository Locations
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

# Set Video Card Drivers
VIDEO_CARDs="virgl"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C
