/*
##
##  Enhancer for YouTube™
##  =====================
##
##  Author: Maxime RF <https://www.mrfdev.com>
##
##  This file is protected by copyright laws and international copyright
##  treaties, as well as other intellectual property laws and treaties.
##
##  All rights not expressly granted to you are retained by the author.
##  Read the license.txt file for more details.
##
##  © MRFDEV.com - All Rights Reserved
##
*/
(function(c){function g(){var b={};this.name?b[this.name]=this.value:b[this.id]=this.checked;chrome.storage.local.set(b)}function Ba(){for(var b=[],d=0;d<r.length;d++)r[d].checked&&b.push(r[d].id);chrome.storage.local.set({controls:b})}function ma(){for(var b=c.querySelectorAll('#customcolors input[type="color"'),d={},n=0;n<b.length;n++)d[b[n].name]=b[n].value;chrome.storage.local.set({customcolors:d})}function na(){fetch(`_locales/${m}/messages.json`).then(function(b){return b.json()}).then(function(b){z=
b.locale_dir.message;c.documentElement.lang=m.replace("_","-");c.body.dir=z;for(var d=v.length-1;0<=d;d--)v[d].textContent=b[v[d].dataset.text].message;for(d=p.length-1;0<=d;d--)p[d].dataset.tooltip=b[p[d].dataset.message].message;c.querySelector("#customcssrules").setAttribute("placeholder",b.custom_theme_instructions.message);c.querySelector("#customscript").setAttribute("placeholder",b.custom_script_instructions.message);chrome.storage.local.set({localecode:m,localedir:z})})}function ca(b){c.body.classList.add("overflow-hidden");
A.style.display="block";b.style.display="block";b.scrollTop=0;A.classList.add("in");setTimeout(function(){c.body.classList.add("modal-open")},50)}function oa(b){c.body.classList.remove("modal-open");setTimeout(function(){b.style.display="none";A.classList.add("fade");A.classList.remove("in");setTimeout(function(){A.style.display="none";c.body.classList.remove("overflow-hidden")},300)},300)}var m=chrome.i18n.getMessage("locale_code"),z=chrome.i18n.getMessage("locale_dir"),v=c.querySelectorAll(".i18n"),
A=c.querySelector("#modal-backdrop"),p=c.querySelectorAll(".player-control .info"),r,w={blur:0,brightness:100,contrast:100,grayscale:0,huerotate:0,invert:0,saturate:100,sepia:0,applyvideofilters:!1,backgroundcolor:"#000000",backgroundopacity:85,blackbars:!1,blockautoplay:!0,blockhfrformats:!1,blockwebmformats:!1,boostvolume:!1,cinemamode:!1,cinemamodewideplayer:!0,controlbar:{active:!0,autohide:!1,centered:!0,position:"absolute"},controls:"loop reverse-playlist volume-booster cards-end-screens cinema-mode size pop-up-player speed video-filters screenshot keyboard-shortcuts options".split(" "),
controlsvisible:!1,controlspeed:!0,controlspeedmousebutton:!1,controlvolume:!1,controlvolumemousebutton:!1,convertshorts:!1,customcolors:{"--main-color":"#00adee","--main-background":"#111111","--second-background":"#181818","--hover-background":"#232323","--main-text":"#eff0f1","--dimmer-text":"#cccccc","--shadow":"#000000"},customcssrules:"",customscript:"",customtheme:!1,darktheme:!1,date:0,defaultvolume:!1,disableautoplay:!1,executescript:!1,expanddescription:!1,filter:"none",hidecardsendscreens:!1,
hidechat:!1,hidecomments:!1,hiderelated:!1,hideshorts:!1,ignoreplaylists:!0,ignorepopupplayer:!0,localecode:m,localedir:z,message:!1,miniplayer:!0,miniplayerposition:"_top-left",miniplayersize:"_400x225",newestcomments:!1,overridespeeds:!0,pauseforegroundtab:!1,pausevideos:!0,popuplayersize:"640x360",qualityembeds:"medium",qualityembedsfullscreen:"hd1080",qualityplaylists:"hd720",qualityplaylistsfullscreen:"hd1080",qualityvideos:"hd720",qualityvideosfullscreen:"hd1080",reload:!1,reversemousewheeldirection:!1,
selectquality:!1,selectqualityfullscreenoff:!1,selectqualityfullscreenon:!1,speed:1,speedvariation:.1,stopvideos:!1,theatermode:!1,theme:"default-dark",themevariant:"youtube-deep-dark.css",update:0,volume:50,volumemultiplier:3,volumevariation:5,wideplayer:!1,wideplayerviewport:!1};chrome.storage.local.get(w,function(b){if(m===b.localecode){c.documentElement.lang=m.replace("_","-");c.body.dir=z;for(var d=v.length-1;0<=d;d--)v[d].textContent=chrome.i18n.getMessage(v[d].dataset.text);for(d=p.length-
1;0<=d;d--)p[d].dataset.tooltip=chrome.i18n.getMessage(p[d].dataset.message);c.querySelector("#customcssrules").setAttribute("placeholder",chrome.i18n.getMessage("custom_theme_instructions"));c.querySelector("#customscript").setAttribute("placeholder",chrome.i18n.getMessage("custom_script_instructions"))}else m=b.localecode,na();c.querySelectorAll("nav a").forEach(function(a){a.addEventListener("focus",function(){this.parentNode.classList.add("focus")});a.addEventListener("blur",function(){this.parentNode.classList.remove("focus")})});
var n=c.querySelector("nav .donate a"),f=c.querySelector("#donate-modal"),pa=f.querySelector(".close-modal");n.addEventListener("click",function(a){a.preventDefault();a=0>"bg ca cs da de el es et fi fr hr hu it lt lv nl pl pt_PT ro sk sl sv".indexOf(m)?"USD":"EUR";f.querySelector(".donate-buttons").dataset.currencyCode=a;ca(f)});f.querySelectorAll(".donate-buttons button").forEach(function(a){a.addEventListener("click",function(){var h=0>"bg ca cs da de el es et fi fr hr hu it lt lv nl pl pt_PT ro sk sl sv".indexOf(m)?
"USD":"EUR";h=n.dataset.paypal.replace(/AMOUNT/,this.dataset.amount).replace(/CURRENCY_CODE/,h);chrome.tabs.create({url:h,active:!0})})});pa.addEventListener("click",function(){oa(f)});d=c.querySelector("#locale");d.value=m;d.addEventListener("change",function(){m=this.value;na()});d.addEventListener("focus",function(){this.parentNode.classList.add("focus")});d.addEventListener("blur",function(){this.parentNode.classList.remove("focus")});"#boostvolume #blackbars #cinemamode #cinemamodewideplayer #reversemousewheeldirection #hidecardsendscreens #hidecomments #hidechat #hiderelated #hideshorts #convertshorts #wideplayer #wideplayerviewport #applyvideofilters #blockhfrformats #blockwebmformats #expanddescription #newestcomments #executescript".split(" ").forEach(function(a){a=
c.querySelector(a);a.checked=b[a.id];a.addEventListener("click",g)});c.querySelector("#keyboard-shortcuts-btn").addEventListener("click",function(){chrome.runtime.sendMessage({request:"configure-keyboard-shortcuts"})});r=c.querySelectorAll('.player-control input[type="checkbox"]');for(d=0;d<r.length;d++)r[d].checked=-1<b.controls.indexOf(r[d].id)?!0:!1,r[d].addEventListener("click",Ba);p=c.querySelectorAll(".player-control .info");for(d=p.length-1;0<=d;d--)p[d].addEventListener("click",function(a){a.preventDefault()});
var k=c.querySelectorAll('input[name="controlbaractive"]'),B=c.querySelector("#controlsvisible"),C=c.querySelector("#controlbarposition"),qa=c.querySelector("#control-bar-centering"),D=c.querySelector("#controlbarcentered"),ra=c.querySelector("#control-bar-visibility"),E=c.querySelector("#controlbarautohide");for(d=0;d<k.length;d++)k[d].value===String(b.controlbar.active)&&(k[d].checked=!0),k[d].addEventListener("click",function(){"false"===this.value?(b.controlbar.active=!1,B.disabled=!1,C.disabled=
!0,D.disabled=!0,E.disabled=!0):(b.controlbar.active=!0,B.disabled=!0,C.disabled=!1,D.disabled=!1,E.disabled=!1);chrome.storage.local.set({controlbar:b.controlbar})});B.checked=b.controlsvisible;B.disabled=b.controlbar.active;B.addEventListener("click",g);C.value=b.controlbar.position;C.disabled=!b.controlbar.active;C.addEventListener("change",function(){qa.classList["absolute"===this.value?"remove":"add"]("hidden");ra.classList["fixed"===this.value?"remove":"add"]("hidden");b.controlbar.position=
this.value;chrome.storage.local.set({controlbar:b.controlbar})});qa.classList["absolute"===b.controlbar.position?"remove":"add"]("hidden");D.checked=b.controlbar.centered;D.disabled=!b.controlbar.active;D.addEventListener("click",function(a){b.controlbar.centered=this.checked;chrome.storage.local.set({controlbar:b.controlbar})});ra.classList["fixed"===b.controlbar.position?"remove":"add"]("hidden");E.checked=b.controlbar.autohide;E.disabled=!b.controlbar.active;E.addEventListener("click",function(a){b.controlbar.autohide=
this.checked;chrome.storage.local.set({controlbar:b.controlbar})});d=c.querySelector("#backgroundcolor");k=c.querySelector("#backgroundopacity");var Ca=c.querySelector("#opacity"),Da=c.querySelector("#cinemamode-background"),da=function(){var a=b.backgroundcolor.replace("#",""),h=parseInt(a.substring(0,2),16),e=parseInt(a.substring(2,4),16);a=parseInt(a.substring(4,6),16);Ca.textContent=b.backgroundopacity+"%";Da.style.backgroundColor=`rgba(${h}, ${e}, ${a}, ${b.backgroundopacity/100})`};d.value=
b.backgroundcolor;d.addEventListener("input",function(){b.backgroundcolor=this.value;da();chrome.storage.local.set({backgroundcolor:this.value})});d.addEventListener("change",g);k.value=b.backgroundopacity;k.addEventListener("input",function(){b.backgroundopacity=Number(this.value);da();chrome.storage.local.set({backgroundopacity:b.backgroundopacity})});da();var F=c.querySelector("#playback-speed"),G=c.querySelector("#custom-playback-speed");d=c.querySelector("#overridespeeds");var L=c.querySelector("#speedvariation");
k=c.querySelector("#defaultvolume");var M=c.querySelector("#volume"),sa=c.querySelector("#volume-preview"),x=c.querySelector("#volumemultiplier"),N=c.querySelector("#controlspeed"),O=c.querySelector("#controlspeedmousebutton"),ta=c.querySelector("#controlvolume"),P=c.querySelector("#controlvolumemousebutton"),Q=c.querySelector("#volumevariation"),ua=c.querySelector("#miniplayer"),R=c.querySelector("#miniplayersize"),S=c.querySelector("#miniplayerposition");F.value=b.overridespeeds?1:b.speed;F.addEventListener("change",
function(){chrome.storage.local.set({speed:parseFloat(this.value)})});G.value=b.overridespeeds?b.speed:1;G.addEventListener("change",function(){chrome.storage.local.set({speed:parseFloat(this.value)})});b.overridespeeds&&(F.classList.add("hidden"),G.classList.remove("hidden"));d.checked=b.overridespeeds;d.addEventListener("click",function(){L.disabled=!this.checked;var a=c.querySelector("#playback-speed-label");a.classList.add("animated","blink");setTimeout(function(){a.classList.remove("animated",
"blink")},2400);F.classList.toggle("hidden");G.classList.toggle("hidden");chrome.storage.local.set({overridespeeds:this.checked,speed:parseFloat(this.checked?G.value:F.value)})});L.value=b.speedvariation;L.disabled=!b.overridespeeds;L.addEventListener("change",function(){chrome.storage.local.set({speedvariation:parseFloat(this.value)})});N.checked=b.controlspeed;N.addEventListener("click",function(){O.disabled=!this.checked;chrome.storage.local.set({controlspeed:this.checked})});O.checked=b.controlspeedmousebutton;
O.disabled=!b.controlspeed;O.addEventListener("click",g);k.checked=b.defaultvolume;k.addEventListener("click",function(){M.disabled=!this.checked;chrome.storage.local.set({defaultvolume:this.checked})});M.value=b.volume;M.disabled=!b.defaultvolume;M.addEventListener("input",function(){b.volume=Number(this.value);sa.textContent=b.volume;chrome.storage.local.set({volume:b.volume})});sa.textContent=b.volume;x.value=b.volumemultiplier;x.addEventListener("change",function(){chrome.storage.local.set({volumemultiplier:Number(this.value)})});
ta.checked=b.controlvolume;ta.addEventListener("click",function(){P.disabled=!this.checked;Q.disabled=!this.checked;chrome.storage.local.set({controlvolume:this.checked})});P.checked=b.controlvolumemousebutton;P.disabled=!b.controlvolume;P.addEventListener("click",g);Q.value=b.volumevariation;Q.disabled=!b.controlvolume;Q.addEventListener("change",function(){chrome.storage.local.set({volumevariation:Number(this.value)})});x.value=b.volumemultiplier;x.addEventListener("change",function(){chrome.storage.local.set({volumemultiplier:Number(this.value)})});
ua.checked=b.miniplayer;ua.addEventListener("click",function(){R.disabled=!this.checked;S.disabled=!this.checked;chrome.storage.local.set({miniplayer:this.checked})});R.value=b.miniplayersize;R.disabled=!b.miniplayer;R.addEventListener("change",g);S.value=b.miniplayerposition;S.disabled=!b.miniplayer;S.addEventListener("change",g);d=c.querySelector("#blockautoplay");var T=c.querySelector("#pauseforegroundtab"),U=c.querySelector("#ignoreplaylists"),V=c.querySelector("#stopvideos");d.checked=b.blockautoplay;
d.addEventListener("click",function(){T.disabled=!this.checked;U.disabled=!this.checked;V.disabled=!this.checked;chrome.storage.local.set({blockautoplay:this.checked})});T.checked=b.pauseforegroundtab;T.disabled=!b.blockautoplay;T.addEventListener("click",g);U.checked=b.ignoreplaylists;U.disabled=!b.blockautoplay;U.addEventListener("click",g);V.checked=b.stopvideos;V.disabled=!b.blockautoplay;V.addEventListener("click",g);d=c.querySelector("#pausevideos");var W=c.querySelector("#ignorepopupplayer");
d.checked=b.pausevideos;d.addEventListener("click",function(){W.disabled=!this.checked;chrome.storage.local.set({pausevideos:this.checked})});W.checked=b.ignorepopupplayer;W.disabled=!b.pausevideos;W.addEventListener("click",g);d=c.querySelector("#disableautoplay");var va=c.querySelector(".autoplay-toggle-button");d.checked=b.disableautoplay;va.setAttribute("aria-checked",!b.disableautoplay);d.addEventListener("click",function(){va.setAttribute("aria-checked",!this.checked);chrome.storage.local.set({disableautoplay:this.checked})});
var ea=c.querySelector("#selectquality"),t=c.querySelector("#selectqualityfullscreenon"),H=c.querySelector("#selectqualityfullscreenoff"),X=["#qualityvideos","#qualityplaylists","#qualityembeds"],Y=["#qualityvideosfullscreen","#qualityplaylistsfullscreen","#qualityembedsfullscreen"];ea.checked=b.selectquality;ea.addEventListener("click",function(){X.forEach(function(a){c.querySelector(a).disabled=!ea.checked});t.disabled=!this.checked;this.checked?(X.forEach(function(a){c.querySelector(a).disabled=
!1}),t.disabled=!1,t.checked&&(Y.forEach(function(a){c.querySelector(a).disabled=!1}),H.disabled=!1)):(X.forEach(function(a){c.querySelector(a).disabled=!0}),t.disabled=!0,Y.forEach(function(a){c.querySelector(a).disabled=!0}),H.disabled=!0);chrome.storage.local.set({selectquality:this.checked})});X.forEach(function(a){a=c.querySelector(a);a.value=b[a.id];a.disabled=!b.selectquality;a.addEventListener("change",g)});t.checked=b.selectqualityfullscreenon;t.addEventListener("click",function(){Y.forEach(function(a){c.querySelector(a).disabled=
!t.checked});H.disabled=!this.checked;chrome.storage.local.set({selectqualityfullscreenon:this.checked})});Y.forEach(function(a){a=c.querySelector(a);a.value=b[a.id];a.disabled=!b.selectqualityfullscreenon;a.addEventListener("change",g)});H.checked=b.selectqualityfullscreenoff;H.addEventListener("click",g);d=c.querySelector("#popuplayersize");d.value=b.popuplayersize;d.addEventListener("change",g);d=c.querySelector("#theatermode");d.checked=b.theatermode;d.addEventListener("click",function(){chrome.cookies.set({url:"https://www.youtube.com/watch",
name:"wide",value:this.checked?"1":"0",domain:".youtube.com",path:"/",expirationDate:Math.floor(Date.now()/1E3)+31556926});chrome.storage.local.set({theatermode:this.checked})});var Z=c.querySelector("#darktheme"),u=c.querySelectorAll('input[name="theme"]'),I=c.querySelector("#themevariant"),fa=c.querySelector("#customcolors"),ha=c.querySelector("#reset-custom-colors");k=c.querySelector("#customtheme");var J=c.querySelector("#customcssrules");x=c.querySelector("#customcssrules-btn");var aa=c.querySelector("#customcssrules-checkmark");
d=u.length-1;Z.checked=b.darktheme;for(Z.addEventListener("click",function(){u.forEach(function(a){a.disabled=!Z.checked});I.disabled=this.checked?"youtube-deep-dark"===c.querySelector('input[name="theme"]:checked').value?!1:!0:!0;c.querySelectorAll('#customcolors input[type="color"]').forEach(function(a){a.disabled=!Z.checked});ha.disabled=!this.checked;chrome.storage.local.set({darktheme:this.checked})});0<=d;d--)u[d].value===b.theme&&(u[d].checked=!0),u[d].disabled=!b.darktheme,u[d].addEventListener("click",
g),u[d].addEventListener("click",function(){I.disabled="youtube-deep-dark"===this.value?!1:!0;fa.classList["youtube-deep-dark-custom"===this.value?"remove":"add"]("hidden")});I.value=b.themevariant;I.disabled=b.darktheme?"youtube-deep-dark"===b.theme?!1:!0:!0;I.addEventListener("change",g);fa.classList["youtube-deep-dark-custom"===b.theme?"remove":"add"]("hidden");var y=fa.querySelectorAll('input[type="color"');N=b.customcolors;for(d=y.length-1;0<=d;d--)y[d].disabled=!b.darktheme,y[d].value=N[y[d].name],
y[d].addEventListener("change",ma);ha.disabled=!b.darktheme;ha.addEventListener("click",function(){var a=w.customcolors;y.forEach(function(h){h.value=a[h.name]});ma()});k.checked=b.customtheme;k.addEventListener("click",function(){J.parentNode.classList[this.checked?"remove":"add"]("hidden");chrome.storage.local.set({customtheme:this.checked})});J.value=b.customcssrules;J.parentNode.classList[b.customtheme?"remove":"add"]("hidden");J.addEventListener("focus",function(){aa.classList.remove("show")});
x.addEventListener("click",function(){aa.classList.add("show");chrome.storage.local.set({customcssrules:J.value})});aa.addEventListener("animationend",function(a){"checkmark-scale"===a.animationName&&setTimeout(function(){aa.classList.remove("show")},1200)});var ia=c.querySelector("#customscript");d=c.querySelector("#customscript-btn");var ba=c.querySelector("#customscript-checkmark");ia.value=b.customscript;ia.addEventListener("focus",function(){ba.classList.remove("show")});d.addEventListener("click",
function(){ba.classList.add("show");chrome.storage.local.set({customscript:ia.value})});ba.addEventListener("animationend",function(a){"checkmark-scale"===a.animationName&&setTimeout(function(){ba.classList.remove("show")},1200)});d=c.querySelector("#export-modal-btn");k=c.querySelector("#import-modal-btn");var l=c.querySelector("#backup-modal"),wa=l.querySelector(".close-modal"),xa=l.querySelector("#export-modal-content"),ya=l.querySelector("#export-textarea"),za=l.querySelector("#import-modal-content"),
ja=l.querySelector("#import-error"),Aa=l.querySelector("#import-textarea"),ka=l.querySelector("#import-btn"),la=l.querySelector("#copy-to-clipboard-btn"),K=l.querySelector("#copy-to-clipboard-checkmark");d.addEventListener("click",function(){xa.classList.remove("hidden");la.classList.remove("hidden");K.classList.remove("hidden");ca(l);chrome.storage.local.get(null,function(a){var h={};h.version=chrome.runtime.getManifest().version;h.settings={};Object.keys(w).forEach(function(e){h.settings[e]="undefined"===
typeof a[e]?w[e]:a[e]});ya.value=JSON.stringify(h)})});k.addEventListener("click",function(){za.classList.remove("hidden");ka.classList.remove("hidden");ca(l)});wa.addEventListener("click",function(){oa(l);setTimeout(function(){xa.classList.add("hidden");za.classList.add("hidden");ja.classList.add("hidden");ka.classList.add("hidden");la.classList.add("hidden");K.classList.add("hidden");Aa.value=""},600)});la.addEventListener("click",function(a){ya.select();c.execCommand("copy");K.classList.add("show")});
K.addEventListener("animationend",function(a){"checkmark-scale"===a.animationName&&setTimeout(function(){K.classList.remove("show")},1200)});ka.addEventListener("click",function(){var a=Aa.value.trim(),h={};if(""!==a){try{a=JSON.parse(a)}catch(q){ja.classList.remove("hidden");return}if("object"===typeof a.settings){a.version&&/2\.0\.(10[3-9]|11[0-9]|12[0-1])/.test(a.version)&&(a.settings.controls=a.settings.controls.filter(q=>"whitelist"!==q&&"not-interested"!==q),delete a.settings.blockads,delete a.settings.blockadsexceptforsubs,
delete a.settings.whitelist);if(a.version&&/2\.0\.103/.test(a.version))"default-light"===a.settings.theme?a.settings.theme="default-dark":a.settings.darktheme=!0;else if(a.version&&/2\.0\.(9|10[0-1])/.test(a.version))try{a.settings.customcolors=w.customcolors;a.settings.customcssrules=a.settings.customtheme;a.settings.customtheme="custom"===a.settings.theme?!0:!1;"default"===a.settings.theme||"custom"===a.settings.theme?(a.settings.themevariant="youtube-deep-dark.css",a.settings.theme="default-dark"):
(a.settings.themevariant=a.settings.theme,a.settings.theme="youtube-deep-dark",a.settings.darktheme=!0);var e=[];e.push("loop");e.push("reverse-playlist");0<=a.settings.toolbarbuttons.indexOf("boost")&&e.push("volume-booster");0<=a.settings.toolbarbuttons.indexOf("cinema")&&e.push("cinema-mode");0<=a.settings.toolbarbuttons.indexOf("resize")&&e.push("size");e.push("pop-up-player");0<=a.settings.toolbarbuttons.indexOf("slowdown")&&e.push("speed-minus");e.push("speed");0<=a.settings.toolbarbuttons.indexOf("speedup")&&
e.push("speed-plus");e.push("video-filters");e.push("screenshot");e.push("keyboard-shortcuts");0<=a.settings.toolbarbuttons.indexOf("script")&&e.push("custom-script");0<=a.settings.toolbarbuttons.indexOf("options")&&e.push("options");a.settings.controls=e;a.settings.applyvideofilters=a.settings.enablefilters;a.settings.blockautoplay=a.settings.autopausevideos;a.settings.customscript=a.settings.script;a.settings.hidecardsendscreens=a.settings.removeannotations;a.settings.miniplayer=a.settings.pinnedplayer;
a.settings.miniplayerposition=a.settings.pinnedplayerposition;a.settings.miniplayersize=a.settings.pinnedplayersize;a.settings.qualityembeds=a.settings.quality2;a.settings.qualityembedsfullscreen=a.settings.quality1;a.settings.qualityplaylists=a.settings.quality1;a.settings.qualityplaylistsfullscreen=a.settings.quality1;a.settings.qualityvideos=a.settings.quality1;a.settings.qualityvideosfullscreen=a.settings.quality1;a.settings.stopvideos=a.settings.disablepreloading;delete a.settings.autofocusevents;
delete a.settings.autopausevideos;delete a.settings.disablepreloading;delete a.settings.enablefilters;delete a.settings.permissions;delete a.settings.pinnedplayer;delete a.settings.pinnedplayerposition;delete a.settings.pinnedplayersize;delete a.settings.quality1;delete a.settings.quality2;delete a.settings.quality3;delete a.settings.quality4;delete a.settings.removeads;delete a.settings.removeannotations;delete a.settings.script;delete a.settings.slideeffect;delete a.settings.toolbarbackgroundcolor;
delete a.settings.toolbarbordercolor;delete a.settings.toolbarbuttons;delete a.settings.toolbarcolor;delete a.settings.toolbarcoloractive;delete a.settings.toolbaropacity;delete a.settings.toolbartooltips;delete a.settings.transparency;delete a.settings.visitor_info1_live}catch(q){}"youtube-deep-dark-youtube-light.css"===a.settings.themevariant&&(a.settings.themevariant="youtube-deep-dark.css");Object.keys(a.settings).forEach(function(q){typeof w[q]===typeof a.settings[q]&&(h[q]=a.settings[q])});
chrome.storage.local.clear(function(){chrome.runtime.lastError&&(c.documentElement.dataset.e=1);chrome.storage.local.set(h,function(){window.scrollTo(0,0);c.location.reload()})})}else ja.classList.remove("hidden")}});c.addEventListener("keydown",function(a){27===a.keyCode&&(wa.click(),pa.click())})});chrome.storage.onChanged.addListener(function(b,d){for(const f in b)if("undefined"!==typeof b[f].newValue)if("darktheme"===f&&b[f].newValue!==c.querySelector("#darktheme").checked)c.querySelector("#darktheme").click();
else if("theme"===f&&b[f].newValue!==c.querySelector('input[name="theme"]:checked').value)c.querySelector(`input[name="theme"][value="${b[f].newValue}"]`).checked=!0,c.querySelector("#themevariant").disabled="youtube-deep-dark"===b[f].newValue?!1:!0,c.querySelector("#customcolors").classList["youtube-deep-dark-custom"===b[f].newValue?"remove":"add"]("hidden");else if("customtheme"===f){d=c.querySelector("#customtheme");var n=c.querySelector("#customcssrules");d.checked!==b[f].newValue&&(d.checked=
b[f].newValue,n.parentNode.classList[b[f].newValue?"remove":"add"]("hidden"))}})})(document);