/*
##
##  Enhancer for YouTube™
##  =====================
##
##  Author: Maxime RF <https://www.mrfdev.com>
##
##  This file is protected by copyright laws and international copyright
##  treaties, as well as other intellectual property laws and treaties.
##
##  All rights not expressly granted to you are retained by the author.
##  Read the license.txt file for more details.
##
##  © MRFDEV.com - All Rights Reserved
##
*/
(function(v,a){if(!v.efyt){var h=new URLSearchParams(a.currentScript.src.split("?")[1]),D=h.get("version"),z=h.get("resources");h="true"===h.get("incognito");function A(){var c=Date.now(),e=c+2592E6;try{b.defaultvolume&&(localStorage["yt-player-volume"]=sessionStorage["yt-player-volume"]=JSON.stringify({data:JSON.stringify({volume:b.volume,muted:!1}),creation:c,expiration:e})),b.selectquality&&(localStorage["yt-player-quality"]=JSON.stringify({data:b[0<location.href.indexOf("list=")?
"qualityplaylists":"qualityvideos"],creation:c,expiration:e})),b.disableautoplay&&(localStorage["yt.autonav::autonav_disabled"]=JSON.stringify({data:!0,creation:c,expiration:e}))}catch(f){}}function w(){x++;var c=a.querySelector("#c4-player");if(c)try{b.stopvideos?c.stopVideo():(c.playVideo(),c.pauseVideo(),c.querySelector(".ytp-spinner").style.display="none")}catch(e){}else 20>x&&(B=setTimeout(w,500))}function E(c){if(!l&&b.stopvideos&&1<=c&&3>=c){g.stopVideo();g.checkTimestamp=!0;try{g.style.backgroundImage=
"url(https://img.youtube.com/vi/"+g.getVideoData().video_id+"/maxresdefault.jpg)",g.style.backgroundSize="100% 100%",g.removeBackgroundImage=!0}catch(e){}}}function r(c){l=!0;a.removeEventListener("keydown",r,!0);a.removeEventListener("mousedown",t,!0)}function t(c){l=!0;a.removeEventListener("keydown",r,!0);a.removeEventListener("mousedown",t,!0)}a.addEventListener("efyt-update-preferences",function(c){b=c.detail.prefs;A()});var l,B,x,g,u;try{var b=JSON.parse(localStorage.getItem("enhancer-for-youtube"))||
{}}catch(c){b={},h||a.dispatchEvent(new Event("efyt-get-preferences"))}h&&a.dispatchEvent(new Event("efyt-get-preferences"));"undefined"===typeof b.blockautoplay&&(b.blockautoplay=!0);"undefined"===typeof b.pausevideos&&(b.pausevideos=!0);"undefined"===typeof b.ignoreplaylists&&(b.ignoreplaylists=!0);b.customcolors||(b.customcolors={"--main-color":"#00adee","--main-background":"#111111","--second-background":"#181818","--hover-background":"#232323","--main-text":"#eff0f1","--dimmer-text":"#cccccc",
"--shadow":"#000000"});b.customcssrules||(b.customcssrules="");b.theme||(b.theme="default-dark");b.themevariant||(b.themevariant="youtube-deep-dark.css");b.qualityvideos||(b.qualityvideos="hd720");b.qualityplaylists||(b.qualityplaylists="hd720");b.volume||(b.volume=50);A();if(b.darktheme&&"default-dark"!==b.theme){if("youtube-deep-dark"===b.theme){var k=a.createElement("link");k.id="efyt-theme-variables";k.rel="stylesheet";k.href=z+"/vendor/themes/"+b.themevariant}else if("youtube-deep-dark-custom"===
b.theme){k=a.createElement("style");k.type="text/css";k.id="efyt-theme-variables";h=[];var y;for([y,m]of Object.entries(b.customcolors)){if("--shadow"===y){var n=m.replace("#","");var m=parseInt(n.substring(0,2),16);var F=parseInt(n.substring(2,4),16);n=parseInt(n.substring(4,6),16);m=`0 1px .5px rgba(${m}, ${F}, ${n}, .2)`}h.push(y+":"+m)}k.textContent=":root{"+h.join(";")+"}"}var p=a.createElement("link");p.id="efyt-theme";p.rel="stylesheet";p.href=z+"/vendor/themes/youtube-deep-dark.material.css?v="+
D;a.head?(a.head.appendChild(k),a.head.appendChild(p)):a.documentElement.addEventListener("load",function f(e){a.head&&(a.documentElement.removeEventListener("load",f,!0),a.head.appendChild(k),a.head.appendChild(p))},!0)}if("Google Inc."===navigator.vendor){var d=a.createElement("style");d.type="text/css";d.textContent="#movie_player div.ytp-chrome-controls button.ytp-pip-button.ytp-button{display: inline-block !important; transform: scaleY(-1)}";a.head?a.head.appendChild(d):a.documentElement.addEventListener("load",
function f(e){a.head&&(a.documentElement.removeEventListener("load",f,!0),a.head.appendChild(d))},!0)}b.customtheme&&(d=a.createElement("style"),d.type="text/css",d.id="efyt-custom-theme",d.textContent=b.customcssrules,a.head?a.head.appendChild(d):a.documentElement.addEventListener("load",function f(e){a.head&&(a.documentElement.removeEventListener("load",f,!0),a.head.appendChild(d))},!0));if(b.hidechat||b.hidecomments||b.hiderelated||b.convertshorts||b.hideshorts)d=a.createElement("style"),d.type=
"text/css",d.id="test",d.textContent='html.efyt-hide-chat ytd-live-chat-frame, html.efyt-hide-comments ytd-item-section-renderer.ytd-comments, html.efyt-hide-comments #comment-teaser.ytd-watch-metadata, html.efyt-hide-comments ytd-engagement-panel-section-list-renderer[target-id="engagement-panel-comments-section"], html.efyt-hide-related ytd-watch-next-secondary-results-renderer, html.efyt-hide-related #related-skeleton.ytd-watch-flexy, html.efyt-hide-related .html5-video-player .html5-endscreen {display: none !important; } html.efyt-convert-shorts ytd-guide-renderer.ytd-app ytd-guide-entry-renderer a[title="Shorts"], html.efyt-convert-shorts ytd-mini-guide-renderer.ytd-app ytd-mini-guide-entry-renderer a[title="Shorts"], html.efyt-hide-shorts ytd-guide-renderer.ytd-app ytd-guide-entry-renderer a[title="Shorts"], html.efyt-hide-shorts ytd-mini-guide-renderer.ytd-app ytd-mini-guide-entry-renderer a[title="Shorts"], html.efyt-hide-shorts .efyt-is-short {display: none !important; } html.efyt-hide-shorts ytd-grid-video-renderer:has(ytd-thumbnail a.yt-simple-endpoint[href^="/shorts/"]), html.efyt-hide-shorts ytd-watch-next-secondary-results-renderer.ytd-watch-flexy ytd-compact-video-renderer:has(ytd-thumbnail a.yt-simple-endpoint[href^="/shorts/"]), html.efyt-hide-shorts ytd-browse[page-subtype="home"] ytd-rich-section-renderer.ytd-rich-grid-renderer:has(ytd-rich-shelf-renderer[is-shorts]), html.efyt-hide-shorts ytd-browse[page-subtype="subscriptions"] ytd-rich-item-renderer.ytd-rich-grid-row:has(a.yt-simple-endpoint[href^="/shorts/"]), html.efyt-hide-shorts ytd-browse[page-subtype="subscriptions"] ytd-item-section-renderer.ytd-section-list-renderer:has(a.yt-simple-endpoint[href^="/shorts/"]), html.efyt-hide-shorts ytd-browse[page-subtype="subscriptions"] ytd-rich-section-renderer.ytd-rich-grid-renderer:has(a.yt-simple-endpoint[href^="/shorts/"]), html.efyt-hide-shorts ytd-browse[page-subtype="trending"] ytd-video-renderer.ytd-expanded-shelf-contents-renderer:has(ytd-thumbnail a.yt-simple-endpoint[href^="/shorts/"]), html.efyt-hide-shorts ytd-browse[page-subtype="trending"] ytd-item-section-renderer.ytd-section-list-renderer:has(ytd-reel-shelf-renderer yt-horizontal-list-renderer a.yt-simple-endpoint[href^="/shorts/"]), html.efyt-hide-shorts ytd-browse[page-subtype="channels"] ytd-item-section-renderer.ytd-section-list-renderer:has(ytd-reel-shelf-renderer yt-horizontal-list-renderer a.yt-simple-endpoint[href^="/shorts/"]), html.efyt-hide-shorts ytd-search.ytd-page-manager ytd-reel-shelf-renderer.ytd-item-section-renderer:has(yt-horizontal-list-renderer a.yt-simple-endpoint[href^="/shorts/"]), html.efyt-hide-shorts ytd-search.ytd-page-manager ytd-video-renderer.ytd-item-section-renderer:has(ytd-thumbnail a.yt-simple-endpoint[href^="/shorts/"]) {display: none !important; }',
a.head?a.head.appendChild(d):a.documentElement.addEventListener("load",function f(e){a.head&&(a.documentElement.removeEventListener("load",f,!0),a.head.appendChild(d))},!0),b.hidechat&&a.documentElement.classList.add("efyt-hide-chat"),b.hidecomments&&a.documentElement.classList.add("efyt-hide-comments"),b.hiderelated&&a.documentElement.classList.add("efyt-hide-related"),b.convertshorts&&a.documentElement.classList.add("efyt-convert-shorts"),b.hideshorts&&a.documentElement.classList.add("efyt-hide-shorts");
var q="/watch"===location.pathname||/\/(v\/|clip\/|live$)/.test(location.pathname)?"watch":/^\/(user|channel|c\/)/.test(location.pathname)?"channel":"browse";a.addEventListener("yt-navigate-start",function(c){"channel"===c.detail.pageType||"watch"===c.detail.pageType?(a.addEventListener("keydown",r,!0),a.addEventListener("mousedown",t,!0),q=c.detail.pageType,l=!1):q=c.detail.pageType;clearTimeout(B)});a.addEventListener("yt-navigate-finish",function(c){"channel"===q&&(x=0,a.hidden?a.addEventListener("visibilitychange",
function f(){a.removeEventListener("visibilitychange",f);setTimeout(w,1E3)}):setTimeout(w,1E3))});HTMLVideoElement.prototype.play=function(c){return function(){u||(u=a.querySelector("yt-playlist-manager"));if(!l&&b.blockautoplay&&("watch"===q||"channel"===q||a.querySelector("ytd-app > ytd-miniplayer[active]"))&&(a.hidden||b.pauseforegroundtab)&&(u&&u.currentPlaylistData_&&!b.ignoreplaylists||0>location.href.indexOf("list=")||!b.ignoreplaylists)&&this.classList.contains("html5-main-video"))g=this.parentNode.parentNode,
b.pausevideos&&this.setAttribute("pausevideos",""),g.pauseVideo(),g.hasAttribute("onstatechange")||(g.setAttribute("onstatechange",""),g.addEventListener("onStateChange",E));else return c.apply(this,arguments)}}(HTMLVideoElement.prototype.play);v.MediaSource&&(MediaSource.isTypeSupported=function(c){return function(e){return b.blockhfrformats&&/framerate=([4-6]\d|\d{3,})/.test(e)||b.blockwebmformats&&/video\/webm/.test(e)?!1:c(e)}}(MediaSource.isTypeSupported));a.addEventListener("keydown",r,!0);
a.addEventListener("mousedown",t,!0);a.hidden||a.addEventListener("visibilitychange",function(){a.hidden&&(l=!0)},!0);a.addEventListener("DOMContentLoaded",function e(){a.removeEventListener("DOMContentLoaded",e);if(!v.Polymer&&"default-dark"!==b.theme){var f=a.head.querySelector("#efyt-theme-variables"),C=a.head.querySelector("#efyt-theme");C&&a.head.removeChild(C);f&&a.head.removeChild(f)}})}})(window,document);